### ISSUE TITLE
Error while running in google colab

### ISSUE THREAD

**Issue by SanatMoharir** [livezingy/tesstrainsh-win#1]
Hi @livezingy,
I was trying to train new fonts(Handwritten) for the tesseract. I Cloned your repo and added my fonts in fonts folder then run tesstrainDone.sh but the following error is coming when I run it on colab.
Can you please help me with this?
![Capture](https://user-images.githubusercontent.com/40124637/81586100-b1957a00-93d2-11ea-91a1-bf0874404b8b.PNG)

**Comment by livezingy** [comment]
@SanatMoharir 
I could not check your picture, could you show your tesstrainDone.sh and the error messages in txt?

**Comment by livezingy** [comment]
@SanatMoharirI 
could you show your tesstrainDone.sh and the whole error messages please? Do you run the tesstrainDone.sh on Windows10? which version of Tesseract?

**Comment by SanatMoharir** [comment]
Hi, @livezingy ,
I am running it on google colab platform and I am using Tesseract 4.00. And the above message was complete error message which I got after running the tesstrainDone.sh file on colab  


**The following is the sh file**:

mkdir -p train
rm -rf train/*

#Update the value of fontlist according to training fonts name
#Update the value of lang according to training language
sh tesstrain.sh \
  --fonts_dir fonts\
  --fontlist 'Alanis Hand Regular' \
  --lang eng  \
  --linedata_only   \
  --langdata_dir langdata_lstm \
  --tessdata_dir tessdata \
  --save_box_tiff \
  --maxpages 10\
  --output_dir train 
  
  mkdir -p output
  rm -rf output/*
  
  #Update eng.traineddata and eng.lstm according to training language to lang.traineddata and lang.lstm
  combine_tessdata -e tessdata/eng.traineddata train/eng.lstm
  
  #Update eng.lstm/eng.traineddata/eng.training_files.txt according to training language
  #Update output/Impact according to training font name
  lstmtraining \
  --continue_from train/eng.lstm \
  --model_output output/Impact \
  --traineddata tessdata/eng.traineddata \
  --train_listfile train/eng.training_files.txt \
  --debug_interval -1\
  --max_iterations 500
  
  #Update eng.traineddata according to training language
  #Update impact_checkpoint and Impact.traineddata according to training font name
  lstmtraining --stop_training \
  --continue_from output/impact_checkpoint \
  --traineddata tessdata/eng.traineddata \
  --model_output output/Impact.traineddata

**Comment by livezingy** [comment]
1. Could you run tesstrainDone.sh successfully on google colab platform with Impact.ttf font in the tesstrainsh-win?
2. where does the Tesseract 4.00 come from?  Is it  compiled by yourself, or from the installed version of UB-Mannheim?
3. Could you show all the error messages from you run the  tesstrainDone.sh to the end?

**Comment by SanatMoharir** [comment]
Hi @livezingy,

Thanks for responding. I left the google colab and now setup fresh leptonica and tesseract on ubuntu. And was trying to train on the fonts which look like handwritten (English language).
 But now whenever I run: 
./tesstrain.sh --fonts_dir fonts --fontlist 'WC Mano Negra Bta' --lang eng --linedata_only --langdata_dir langdata_lstm --tessdata_dir tessdata --save_box_tiff --maxpages 10 --output_dir train

The Following error came out:


=== Starting training for language 'eng'
[Tue May 12 18:13:13 IST 2020] /usr/local/bin/text2image --fonts_dir=fonts --ptsize 12 --font=WC Mano Negra Bta --outputbase=/tmp/font_tmp.Qn6Ufax3iC/sample_text.txt --text=/tmp/font_tmp.Qn6Ufax3iC/sample_text.txt --fontconfig_tmpdir=/tmp/font_tmp.Qn6Ufax3iC
Error in pixWriteTiff: function not present
Rendered page 0 to file /tmp/font_tmp.Qn6Ufax3iC/sample_text.txt.tif

=== Phase I: Generating training images ===
Rendering using WC Mano Negra Bta
[Tue May 12 18:13:14 IST 2020] /usr/local/bin/text2image --fontconfig_tmpdir=/tmp/font_tmp.Qn6Ufax3iC --fonts_dir=fonts --strip_unrenderable_words --leading=32 --xsize=3600 --char_spacing=0.0 --exposure=0 --outputbase=/tmp/eng-2020-05-12.3XK/eng.WC_Mano_Negra_Bta.exp0 --max_pages=10 --font=WC Mano Negra Bta --ptsize 12 --text=langdata_lstm/eng/eng.training_text
Stripped 3 unrenderable words
Error in pixWriteTiff: function not present
Rendered page 0 to file /tmp/eng-2020-05-12.3XK/eng.WC_Mano_Negra_Bta.exp0.tif
Stripped 4 unrenderable words
Error in pixWriteTiff: function not present
Rendered page 1 to file /tmp/eng-2020-05-12.3XK/eng.WC_Mano_Negra_Bta.exp0.tif
Stripped 5 unrenderable words
Error in pixWriteTiff: function not present
Rendered page 2 to file /tmp/eng-2020-05-12.3XK/eng.WC_Mano_Negra_Bta.exp0.tif
Stripped 1 unrenderable words
Error in pixWriteTiff: function not present
Rendered page 3 to file /tmp/eng-2020-05-12.3XK/eng.WC_Mano_Negra_Bta.exp0.tif
Stripped 6 unrenderable words
Error in pixWriteTiff: function not present
Rendered page 4 to file /tmp/eng-2020-05-12.3XK/eng.WC_Mano_Negra_Bta.exp0.tif
Stripped 3 unrenderable words
Error in pixWriteTiff: function not present
Rendered page 5 to file /tmp/eng-2020-05-12.3XK/eng.WC_Mano_Negra_Bta.exp0.tif
Stripped 5 unrenderable words
Error in pixWriteTiff: function not present
Rendered page 6 to file /tmp/eng-2020-05-12.3XK/eng.WC_Mano_Negra_Bta.exp0.tif
Stripped 4 unrenderable words
Error in pixWriteTiff: function not present
Rendered page 7 to file /tmp/eng-2020-05-12.3XK/eng.WC_Mano_Negra_Bta.exp0.tif
Stripped 2 unrenderable words
Error in pixWriteTiff: function not present
Rendered page 8 to file /tmp/eng-2020-05-12.3XK/eng.WC_Mano_Negra_Bta.exp0.tif
Stripped 4 unrenderable words
Error in pixWriteTiff: function not present
Rendered page 9 to file /tmp/eng-2020-05-12.3XK/eng.WC_Mano_Negra_Bta.exp0.tif
ERROR: /tmp/eng-2020-05-12.3XK/eng.WC_Mano_Negra_Bta.exp0.tif does not exist or is not readable


What is this am am not able to get it. Can you please help me with this?

Or can you please help me with training the handwritten fonts file (As I just want to see if training tesseract on Handwritten-like fonts can Improve accuracy of actual handwritten Images). If this wont work so I can move on with some other approaches 

Here is My drive Link For Fonts : [(https://drive.google.com/drive/folders/1oxPcVKBjI8916HrpDK-QPgUWDfLgxiwz?usp=sharing)]

If you have time could you please send me the trained model?
my email is [(yofootball11@gmail.com)]

Your help will be very much appreciated !!!!

**Comment by livezingy** [comment]
Hi, @SanatMoharir 
1.  I have train the AlanisHand font and I test it with lstmeval. It seems that the new traineddata is better than the eng.traineddata. Please check the mail.
the eng.traineddata lstmeval results:
```
At iteration 0, stage 0, Eval Char error rate=92.13522, Word error rate=83.682578
```
the new traineddata lstmeval results:
```
At iteration 0, stage 0, Eval Char error rate=17.597954, Word error rate=36.572861
```
Try more iterations training would get more better lstmeval results.

2. the error "Error in pixWriteTiff: function not present" when you train may be the problem of leptonica. Please Refer to https://github.com/tesseract-ocr/tesseract/issues/2483
